name: my-site
services:
  server:
    image: hugomods/hugo:exts-0.128.2
    command: hugo server --disableFastRender --noChmod --bind 0.0.0.0 --buildDrafts
    volumes:
      - $PWD:/src
      - $HOME/hugo_cache:/tmp/hugo_cache
    ports:
      - 1313:1313