baseURL = 'https://codemageddon.me/'
languageCode = 'en'
defaultContentLanguage = "en"
title = "Codemageddon's corner"
author = "Codemageddon"
copyright = "Codemageddon"
theme = "tailwind"
enableInlineShortcodes = true
paginate = 10

[pagination]
pageSize = 10

[params]
contentTypeName = "post"

[params.author]
name = "Codemageddon"


[params.header]
logo = "logo_v1.png"

[params.footer]
since = 2024
poweredby = true

[menu]
[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 0

[[menu.main]]
identifier = "post"
name = "Post"
pageRef = "/post"
weight = 1000


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup]
  _merge = "deep"

[markup.goldmark.renderer]
unsafe= true